--GET TABLE List from DB
SELECT TABLE_CATALOG,
       TABLE_SCHEMA,
       TABLE_NAME,
       TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES
ORDER BY TABLE_TYPE


--GET List of Columns
SELECT TABLE_CATALOG,
       TABLE_SCHEMA,
       TABLE_NAME,
       COLUMN_NAME,
       ORDINAL_POSITION,
       IS_NULLABLE
       --*
FROM INFORMATION_SCHEMA.COLUMNS
ORDER BY TABLE_NAME

--Check Table Privileges by account -- Which account has access to which tables
SELECT GRANTOR,
       GRANTEE,
       TABLE_CATALOG,
       TABLE_SCHEMA,
       TABLE_NAME,
       PRIVILEGE_TYPE,
       IS_GRANTABLE
FROM INFORMATION_SCHEMA.TABLE_PRIVILEGES

--??? value not that good?
SELECT * FROM  INFORMATION_SCHEMA.VIEW_TABLE_USAGE

EXEC sys.sp_help 'dbo.Test' -- Table Name

SELECT @@VERSION

SELECT @@IDENTITY

SELECT SCOPE_IDENTITY()



